### ISSUE TITLE
recapitate tree sequence after spliting it with keep_intervals()

### ISSUE THREAD

**Issue by mnavascues** [tskit-dev/pyslim#104]
This is a follow up from my question on [slim-discuss](https://groups.google.com/forum/#!topic/slim-discuss/UIwmOPuv9Ww).

Starting with a large tree sequence produced with SLiM (22 "chromosomes") I want to split it on 44 intervals (chromosome arms) and recapitate each of those intervals. But the output of keep_intervals() is of class TreeSequence so I get error:

AttributeError:  'TreeSequence' object has no attribute 'recapitate'

**Comment by mnavascues** [comment]
I see now that I can save the tree sequence tables and use pyslim.load_tables() to get the tree sequence as a SlimTreeSequence object.

**Comment by petrelharp** [comment]
yes - or, you can just do
```
pyslim.SlimTreeSequence(ts.keep_intervals(...))
```
