### ISSUE TITLE
union and metadata

### ISSUE THREAD

**Issue by mufernando** [tskit-dev/pyslim#105]
I think we need a pyslim wrapper around `union` in pyslim, mostly to deal with top-level metadata.

e.g., right now if you union two SLiM tree sequences and try to recapitate the unified ts, you might get sth that doesn't make sense, because `slim_generation` is wrong.

**Comment by petrelharp** [comment]
Do you have a proposal for how this should work?

**Comment by mufernando** [comment]
I haven't thought deeply about how to do this yet, but I think sth along these lines

```
def pyslim_union(ts1, ts2, node_mapping):
    # TODO: time shift?
    tsu = ts1.union(ts2, node_mapping)
    tsu = pyslim.load_tables(tsu.tables)
    assert tsu.max_root_time.is_integer()
    # TODO: anything else that we need to change? don't remember SLiM's top-level schema
    tsu = pyslim.annotate_defaults(tsu, tsu.metadata["SLiM"]["model_type"], int(tsu.max_root_time))
    return(tsu)
```

**Comment by petrelharp** [comment]
Sounds good - basically, set the model type to that of ts1 and slim_generation to the max of the two, since this is what union does? Here's a rewrite of what you had:
```
def pyslim_union(ts1, ts2, node_mapping):
    # TODO: time shift?
    tables = ts1.tables
    tables.union(ts2.tables, node_mapping)
    time1 = ts1.metadata['SLiM']['generation']
    time2 = ts2.metadata['SLiM']['generation']
    md = ts1.metadata
    md['generation'] = max(time1, time2)
    tables.metadata = md
    return(pyslim.load_tables(tables))
```

[Here's an example](https://github.com/tskit-dev/pyslim/blob/main/pyslim/slim_metadata.py#L366) of the top-level metadata, btw.

**Comment by petrelharp** [comment]
I think that if we do this, it should not be a wrapper around union, but rather a differently-named method to do whatever the common operation is here. If it's really so similar to union, then we should just document how to do it as a vignette and not provide the wrapper. What do you think, @mufernando? I think it's a generally useful enough operation that it's worth definiing it?

**Comment by mufernando** [comment]
I agree it is worth defining it. Also probably better to deal with time shift within it, and provide a vignette which shows a couple of examples of `pyslim.union`. Though now I remember you might've already written a vignette for this.

**Comment by petrelharp** [comment]
> Though now I remember you might've already written a vignette for this.

I've written one: https://pyslim.readthedocs.io/en/latest/vignette_continuing.html

**Comment by petrelharp** [comment]
Can we close this, @mufernando?

**Comment by mufernando** [comment]
yeah, sorry I duplicated this heh
