### ISSUE TITLE
make tests parallelizable

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#114]
Right now, using `-n 4` with pytest produces errors, probably due to shared files. It would be nice if we could run the tests in parallel, though! Switching test's temporary files over to use pytest's fixtures (as [here](https://github.com/tskit-dev/pyslim/blob/f27d244b3d3393652760cae129b6445ff51323f1/tests/test_tree_sequence.py#L65)) might do it.

**Comment by petrelharp** [comment]
Here's how it works, @hyanwong:
- all the `examples/recipe_*.slim` recipes are run [at the start, by this code](https://github.com/tskit-dev/pyslim/blob/main/tests/conftest.py), since they just need to be run once only, though all the tests use the results.
- tests use the results through [`get_slim_examples( )`](https://github.com/tskit-dev/pyslim/blob/main/tests/__init__.py#L118), which looks up what tests there are and have what attributes in [this dict](https://github.com/tskit-dev/pyslim/blob/main/tests/__init__.py#L28)
- but the problem with parallelization at the moment is in doing [restarts](https://github.com/tskit-dev/pyslim/blob/main/tests/__init__.py#L151), since a number of tests will (a) take a tree sequence (b) save it out to a file with a pre-specified name (c) do something with it. If more than one test tries to do the same restart at the same time they'll conflict with each other.

So, I think switching the file usage in `get_slim_restarts( )` to tempfiles would fix the problem (and probably `get_msprime_restarts( )`).

**Comment by hyanwong** [comment]
> Here's how it works, @hyanwong:

Thanks Peter

> * all the `examples/recipe_*.slim` recipes are run [at the start, by this code](https://github.com/tskit-dev/pyslim/blob/main/tests/conftest.py), since they just need to be run once only, though all the tests use the results.

I've just been chatting to @benjeffery about this (in the context of the treerec tests within the SLiM repo), and he suggested that the recipes should be parameters to a fixture, and the fixture can have session-level data (i.e. from simulations) which is set up once-only. He pointed me to https://github.com/pytest-dev/pytest-xdist#making-session-scoped-fixtures-execute-only-once

> * tests use the results through [`get_slim_examples( )`](https://github.com/tskit-dev/pyslim/blob/main/tests/__init__.py#L118), which looks up what tests there are and have what attributes in [this dict](https://github.com/tskit-dev/pyslim/blob/main/tests/__init__.py#L28)

If it were a fixture, then I guess each of these examples would be a parameter

> * but the problem with parallelization at the moment is in doing [restarts](https://github.com/tskit-dev/pyslim/blob/main/tests/__init__.py#L151), since a number of tests will (a) take a tree sequence (b) save it out to a file with a pre-specified name (c) do something with it. If more than one test tries to do the same restart at the same time they'll conflict with each other.

Don't we want to save the files from each example in a separate dir?

**Comment by hyanwong** [comment]
By the way @petrelharp - are the basic requirements the same as in `SLiM/treerec/tests` - i.e. run a SLiM recipe, get some outputs, run a whole bevvy of tests on the outputs, run another recipe, repeat...

If so, I wonder if it would be easier to get proper parallelisation & fixtures working in the SLiM tests first (which are simpler, I think), and then port that scheme here?

**Comment by petrelharp** [comment]
Well, this isn't the same set-up as in SLiM/treerec/tests (this is a proper pytest set-up; that is pretty ad-hoc). This is not doing "run a SLiM recipe, get some outputs, run a whole bevvy of tests on the outputs, run another recipe, repeat..." - which tests run on which SLiM examples is not so straightforward; see usages of `get_slim_examples( )`. But, if you figure out the right way to do SLiM/treerec/tests in a proper pytest way then I think it'd show the way forward over here?

**Comment by hyanwong** [comment]
> if you figure out the right way to do SLiM/treerec/tests in a proper pytest way then I think it'd show the way forward over here?

See suggestion in https://github.com/MesserLab/SLiM/issues/140

**Comment by hyanwong** [comment]
I think this can be closed now @petrelharp ?

**Comment by petrelharp** [comment]
Closed in #131
