### ISSUE TITLE
tutorial feature: loading a coalescent sim with overlaid mutations into SLiM

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/pyslim#121]
This will depend upon msprime 1.0's support for mutating at discrete positions.  I was planning on it being a recipe 17.11 in the SLiM manual, but as per our recent discussion, it probably belongs on the pyslim side of the doc since it's pretty advanced and all the interesting stuff happens on the python side.  It would be good for the recipe to have a rationale for *why* one would want to do this.  An easy rationale is probably: "You want to do a long burn-in, back to coalescence, and then you want one of the mutations that comes from that burn-in history to change from neutral to selected, due to a change in the environment."

**Comment by petrelharp** [comment]
We've got this, I think? https://tskit.dev/pyslim/docs/latest/vignette_coalescent_diversity.html  Re-open if not.
