### ISSUE TITLE
remove attrs and python 3.6

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#124]
See https://github.com/tskit-dev/msprime/pull/1369

**Comment by jeromekelleher** [comment]
I've nothing against attrs btw, it just seemed sensible to avoid adding the dependency to msprime since we're doing such a big update anyway.

But supporting the last 3 versions of Python seems like a good approach, and might as well use dataclasses if py37 is the oldest.

**Comment by petrelharp** [comment]
closed in #154
