### ISSUE TITLE
look into missing restart_and_run tests

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#133]
In `tests/recipe_specs.py` we have
```
     #"restart_and_run_WF.slim":    {"WF": True, "input": "recipe_init_mutated.slim"},
```
which is supposed to say `recipe_init_mutated_WF.slim`, I think?  What's going on?

**Comment by hyanwong** [comment]
There are also no recipes starting "`restart_and_runXXXX`" in examples/. I don't know what the recipe should look like. I guess we used to have some like that?

**Comment by petrelharp** [comment]
My best guess is that I started to implement something like that, but then got sidetracked and it accidentally got swept up in some other commits. I'll look into it.
