### ISSUE TITLE
Make test suite names match those in SLiM treerec tests?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/pyslim#134]
A few trivial changes, but the directory with test recipes in the SLiM tests is called "testRecipes", whereas in pyslim it is called "examples". 

I wonder if we should change the name here to match that in SLiM (or move both to `test_recipes`)? Also it's not clear to me what the existing "recipes" directory is for - I don't think it's used in an automated way, right?

Also I wonder whether to `s/basic_recipe/recipe/` in the fixture name? I put "basic_" in there to distinguish them from the restarted_recipes, but I think that's not really needed. I think the shortening of the name might make the `@pytest` decorators all fit on one line, which would make it much clearer what's going on in some instances. It should be obvious what a fixture named `recipe` does, right @petrelharp ?

I'm happy to make a quick PR with these changes.

**Comment by petrelharp** [comment]
It's really great to get some more eyes on this code!

- rename `examples/`? Sure - I like `test_recipes`.
- get rid of `recipes`? I'd just noticed that, too! Forgot they were there! We can delete them, and put them back in later properly if so motivated.
- rename `basic_recipe` -> `recipe`. Totaly. Good idea. I wondered what the "basic" meant (but figured it out).

> I'm happy to make a quick PR with these changes.

That'd be awesome.

**Comment by hyanwong** [comment]
Great. The PR with these changes is actually based on the "support-retain" branch, so I'll sort that out first.

**Comment by hyanwong** [comment]
> * get rid of `recipes`? I'd just noticed that, too! Forgot they were there! We can delete them, and put them back in later properly if so motivated.

It looks like the Makefile in there might do something, but I wasn't sure what. Happy to delete the whole thing, though!

**Comment by petrelharp** [comment]
> It looks like the Makefile in there might do something, but I wasn't sure what. Happy to delete the whole thing, though!

Hm, right, I forgot it was all so nicely set up. Let's leave it, it's not hurting anything. (and add this to the things that github runs for PRs, if it isn't too slow)

**Comment by petrelharp** [comment]
I think we can close this, @hyanwong?

**Comment by hyanwong** [comment]
Looks like it
