### ISSUE TITLE
'SlimTreeSequence' object has no attribute 'individual_parents'

### ISSUE THREAD

**Issue by raeckel** [tskit-dev/pyslim#135]
Hello, I've encountered an issue concerning the following code:

import pyslim
ts = pyslim.load("recipe_17.5.trees")
ts.individual_parents()

This code runs with no issues on my own PC, but when I try to run it on a different machine I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SlimTreeSequence' object has no attribute 'individual_parents'

Both pyslim (0.501) and msprime (1.0.0a3) are the same version on both computers, so is tskit (0.3.4). The only difference seems to be a minor variation in python version (3.8.7 instead of 3.8.5). I used the same file on both PCs, yet the attribute "individual_parents" doesn't seem to exist on one of them. I assume that I forgot to install some package or something like that but I can't seem to figure out what I'm doing wrong. What am I missing?

Thank you for your time.

**Comment by petrelharp** [comment]
Hm, sorry to hear it! Could you stick the line `print(pyslim.__version__)` into the troublesome script, to double-check what version it's using?

**Comment by raeckel** [comment]
Sure, no problem! 
It confirmed that it's running version 0.501.

**Comment by petrelharp** [comment]
Oh, sorry! My bad - the `individual_parents` method is not yet released - if you want to use it you'll need to install pyslim from github.  But, we're going to put out another release "any minute"; it's just waiting on #125. (so, "any minute" means a week?)

I'm going to close this, but feel free to re-open if you need further assistance.
