### ISSUE TITLE
Define attributes in Sphinx to allow linking

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/pyslim#138]
In the `rst` docs, we often reference e.g. 

```
:attr:`.SlimTreeSequence.individual_locations`
```

But at the moment those don't get auto-linked to the API documentation. It would be nice to change the way of listing the attributes in the `.SlimTreeSequence` docstrings to allow this sort of crosslinking.

**Comment by petrelharp** [comment]
Since we don't have `SlimTreeSequence` any more (or, any classes), I think this is not relevant? (re-open if I"m missing something?)
