### ISSUE TITLE
Release that works with current msprime 1.0 alpha

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/pyslim#141]
The currently released version of pyslim doesn't work with msprime alphas because it's using  APIs that didn't make it into the actual release.

The simplest way to fix the code, I think, is to do 
```
recombination_map = msprime.RecombinationMap(
                   positions = [0.0, self.sequence_length],
                   rates = [recombination_rate, 0.0],
                   num_loci = int(self.sequence_length))
```

in all cases, and to get rid of the ``discrete_msprime`` thing [here](https://github.com/tskit-dev/pyslim/blob/4fa846bea0c15e9c06cec943671fdf5291636e29/pyslim/slim_tree_sequence.py#L445)

Msprime 1.0 should be fully compatible with code doing discrete simulations the old-school way, so this workaround isn't needed any more.

It would be good to get this released soon, so that pyslim users code won't break when msprime 1.0 is released. It's also stopping us from getting the stdpopsim test suite working with msprime 1.

**Comment by petrelharp** [comment]
Yes, thanks for the nudge.

**Comment by petrelharp** [comment]
I guess that #144 didn't resolve this issue, since you need a *release*. I'm getting ready to do this. I guess that this release shouldn't actually *depend on* the msprime alpha, though.

**Comment by jeromekelleher** [comment]
No, we just want a release so that pyslim users code won't break when they update to msprime 1, in a month or so.

**Comment by jeromekelleher** [comment]
Mainly though it's to unblock progress on stdpopsim - we can't get ci passing on msprime 1 development there until this is released. I guess we could install from git though, if there's stuff queued up that needs to be done before release?

**Comment by petrelharp** [comment]
I think I can release now (ie tomorrow) - there's a few things that won't make sense until SLiM 3.6 is released, at the end of the week, but that's fine, nothing is broken.
