### ISSUE TITLE
move `reference_sequence` to metadata?

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#147]
Some of the ugliness we currently have has to do with preserving the reference sequence, which recall is stored as a separate column in the kastore. However, if it was just top-level metadata, then we'd get it passed around for free, and we could get rid of a number of ugly things, for instance, the need for [a wrapper on simplify](https://github.com/tskit-dev/pyslim/blob/main/pyslim/slim_tree_sequence.py#L290). However, this would require a change in how SLiM writes it out as well.

However, maybe we're just going to put support for reference sequences into tskit; if so, we should just wait for that. If not, we should definitely move it to metadata.

**Comment by petrelharp** [comment]
Relies on https://github.com/MesserLab/SLiM/issues/180

**Comment by benjeffery** [comment]
Discussion of ref seq in tskit is here: https://github.com/tskit-dev/tskit/issues/146 It seems overdue to add tskit support for the reference sequence.
