### ISSUE TITLE
Use SlimTreeSequence to automatically decode metadata

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/pyslim#16]
We can use the ``SlimTreeSequence`` to automatically decode the metadata by overriding the (e.g.) [invidual](https://github.com/tskit-dev/msprime/blob/master/msprime/trees.py#L2252) method:

```python
class SlimTreeSequence(msprime.TreeSequence):

    def individual(self, id_):
         ind = super(SlimTreeSequence, self).individual(id_)
         ind.metadata = IndividualMetadata.decode(ind.metadata)
         return ind
```

This would be a major advantage of the subclass approach, and should be quite robust to changes.

**Comment by petrelharp** [comment]
Totally. Hm, and I see this would change propagate to the `.individuals()` iterator, very nice.

**Comment by petrelharp** [comment]
I made a start at this in #26 (commented out though). It will be non-backwards-compatible, so all changes like this ought to happen at once: e.g. #6.

**Comment by petrelharp** [comment]
This is done, at #37
