### ISSUE TITLE
add tests for weird handcrafted ts behavior

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#163]
See https://github.com/MesserLab/SLiM/issues/178 for instance - should test
- duplicate pedigree IDs
- duplicate mutation IDs
- mismatching mutation information
- mismatching genome + individual IDs
- ... others?

**Comment by petrelharp** [comment]
I'm not sure what this means to "test" - is this a duplicate of #62? Any insight, @bhaller?

**Comment by bhaller** [comment]
Yes, I read it as "test *for*, and give an error if found", so I think it's a dup of #62.  The only thing before closing it would be to check that the four specific ideas mentioned above are all on the radar in #62, also, as problems we might want to test for.

**Comment by petrelharp** [comment]
Closing in favor of #62.
