### ISSUE TITLE
provide method to remap alleles (eg for VCF output)

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#168]
Sometimes we'd like to be able to change what the ancestral/derived states are, for instance, for doing VCF output of a SLiM-produced tree sequence. In tskit-dev/tskit#1081 we decided that the way to do this is to provide a method that remaps alleles. It's pretty easy to do this by hand now, so I'm not sure at what level of generality the API should work. In tskit-dev/tskit#1081 I proposed [having the method take a callable that takes in a Variant and return a list of new alleles](https://github.com/tskit-dev/tskit/pull/1081/files#diff-ecbb802115b51a593926a3015f4ff2ec444fa4dc4915af74f4959abc60c84df8R4747). This is on the one hand probably too general - we should be trying to make the common use case of converting things to nucleotides very easy - and not completely general - since distinct mutations can have the same derived allele, and this wouldn't let us remap those to different alleles.

For the SLiM-to-VCF problem, I think we want to do something like this, to get unique alleles for each mutation:
```python
import tskit, msprime
import random

ts = msprime.sim_ancestry(10, recombination_rate=0.01, sequence_length=100)
ts = msprime.sim_mutations(ts, rate=0.01, model=msprime.SLiMMutationModel(type=0))
t = ts.tables
t.sites.clear()
t.mutations.clear()

def make_alleles(n):
    nucs = ['A', 'C', 'G', 'T']
    alleles = nucs.copy()
    random.shuffle(alleles)
    while len(alleles) < n:
        new = [a + b for a in alleles for b in nucs]
        random.shuffle(new)
        alleles.extend(new)
    return alleles[:n]

for s in ts.sites():
    alleles = make_alleles(len(s.mutations) + 1)
    t.sites.append(s.replace(ancestral_state=alleles[0]))
    for j, m in enumerate(s.mutations):
        t.mutations.append(m.replace(derived_state=alleles[j+1]))

mts = t.tree_sequence()
for h in mts.haplotypes():
    print(h)
```

**Comment by jeromekelleher** [comment]
The ``append`` method is part of tskit 0.3.6 @jydu, which is due for release this week. You can use the ``add_row`` method instead for now, which is a bit more tedious because you have to unpack the rows manually.

**Comment by jydu** [comment]
Thanks! I'll wait a few days then... :)

**Comment by petrelharp** [comment]
This is done for nucleotide models in https://github.com/tskit-dev/pyslim/pull/174

**Comment by hyanwong** [comment]
> That makes sense. Any other use cases for remapping alleles?

Apart from changing the ancestral state? Perhaps if you want to remap all the alleles so they are listed in the same order for all sites (e.g. https://tskit.dev/tskit/docs/stable/python-api.html#tskit.ALLELES_ACGT)?

**Comment by petrelharp** [comment]
That's a different issue, isn't it @hyanwong? I am talking about actually changing the `ancestral_state` or `derived_state` column; but are you talking about the order they appear in the `alleles` attribute of the Variants iterator, for instance?

**Comment by hyanwong** [comment]
Yes, you're right: I'm getting confused. That's a `Variants` thing.

**Comment by hyanwong** [comment]
Thinking about this a bit more, what happens if we augment a tree sequence by adding another sample (supposing such a thing were possible), and that sample maps higher up than the existing root of the tree, revealing a mutation above the exiting root, and changing the ancestral state?

**Comment by petrelharp** [comment]
That would have to change the ancestral state in the tables, yes - what are you thinking about?

**Comment by hyanwong** [comment]
I was just trying to think of examples where we might want to change the ancestral state at a site. One is where we have simply mixed it up with one of the derived states (i.e. we've polarised it wrongly). Another is where we have it right for that tree sequence, but where we want to place a new mutation above the root, which will change the ancestral state, possibly to some state that is has not yet been seen at that site. I';m not sure I'm helping here though: I'm just mooting possibilities.

**Comment by petrelharp** [comment]
Ah, ok. That seems like a fairly different use case, as we'd need to actually add new nodes and mutations. In the VCF remapping example everything stays the same except that the ancestral and derived state columns might change, and these would be changed separately for each site.
