### ISSUE TITLE
add method to get the largest SLiM mutation ID

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#179]
... so we know where to start mutating from

**Comment by petrelharp** [comment]
... as is done [here](https://github.com/popsim-consortium/stdpopsim/blob/de8c2150b4f569b6a3ed1bd7d6d9d2e12b02ba82/stdpopsim/slim_engine.py#L1306) for instance.

**Comment by bhaller** [comment]
Easy and useful, right?

**Comment by petrelharp** [comment]
This is done in #290.
