### ISSUE TITLE
Importing mutations from msprime

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/pyslim#19]
At the moment, annotate_defaults() does not convert the continuous-valued positions of mutations in .trees file into integer values, as is required by SLiM. (When the resulting SlimTreeSequence is loaded into SLiM, an error results.) This means that only .trees files without mutations can be fed into SLiM.

There's already some discussion of this [here](https://github.com/tskit-dev/pyslim/commit/f0229ba611cf54f310756114bd669bf67e6ed930) and [here](https://github.com/tskit-dev/msprime/issues/553).

**Comment by petrelharp** [comment]
> So, the main thing you'd need here is to be able to generate mutations at integer sites, which would happen on the msprime side.

This is done!!
