### ISSUE TITLE
Add "<" to struct definitions

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/pyslim#2]
I had a quick scan over the unpacking code, and it's looking good.

One minor issue though: the struct.pack/unpack format strings should explicitly state that the values are little-endian. The main reason here is to ensure that standard sizes for ints etc, otherwise they are defined by the compiler which can vary.

Changing to
```
struct.unpack("<ifii", buff)
```
states that they are little-endian and standard sizes. It's very unlikely that any of this will ever be used on a big-endian system so we might as well be explicit about requiring things be stored in little endian format.

If this seems overly prescriptive, then we can use the '=' prefix which says to use native byte ordering but standard sizes. We should *definitely* use one of '<' or '=' as the prefix though.

**Comment by petrelharp** [comment]
This also affects padding; for one of these I had to use `=` already. I'll switch 'em to `<` though.

**Comment by petrelharp** [comment]
Done in 3b8a3ff23f95ace9
