### ISSUE TITLE
adjust to new nucleotide reference sequence location

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/pyslim#206]
Now that https://github.com/MesserLab/SLiM/issues/180 is fixed, pyslim needs to look for the reference sequence in top-level metadata instead of in kastore, for `file_version` 0.7 and later, under the key `ts.metadata["reference_sequence"]`.

**Comment by petrelharp** [comment]
Actually, it's in `ts.reference_sequence` :tada:. Closed in b34a853674abc67cc12a455f67ec13c6fa0246bd
