### ISSUE TITLE
Simplifying a recapitated .trees file produces weird (wrong?) output

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/pyslim#21]
Hi again,

I've noticed that when I run ```simplify()``` on recapitated TreeSequences in my simulation pipeline, the output doesn't look quite right. 
I've made [a short notebook](https://github.com/gtsambos/AdmixtureSim/blob/thin-samples/x.errors/3.simplify-problem.ipynb) that illustrates my problem.

**Comment by petrelharp** [comment]
Gee, you had me worried! But I think found the mistake - you've simplified the tree sequence that hasn't been recapitated - instead of
```
ts_simplified = ts.simplify([10,11,12,13,14,15])
```
it should be
```
ts_simplified = ts_recap.simplify([10,11,12,13,14,15])
```

Easy mistake to make!  Very nice writeup, btw.  I will close this; please re-open if this is not the problem.

**Comment by gtsambos** [comment]
Ugh, sorry for cluttering your issues page with silly mistakes -____- and thanks for the debugging help!!

**Comment by petrelharp** [comment]
No problem! Happens to everyone. =)
