### ISSUE TITLE
monitor memory and do gc

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#211]
See https://tskit-dev.slack.com/archives/CVD28GG5T/p1638499698160200 and surrounding discussion - `pyslim.load( )` needs some manual gc, seems like.

**Comment by benjeffery** [comment]
We have some big changes coming down the pipe to do with memory management, hoping those will fix this.

**Comment by bhaller** [comment]
Obsolete I think?  `pyslim.load()` is not a thing any more, right?
