### ISSUE TITLE
mention time units

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#222]
Now there's [time units] to deal with; does this need to be mentioned somewhere? Maybe even document how to change them?

**Comment by bhaller** [comment]
This strikes me as perhaps important, especially now that SLiM usually calls the time unit "ticks" which often triggers a warning from tskit (and rightly so).  Discussion of the time unit concept, what to do about the warning, etc., will be an FAQ once SLiM 4 is out.

**Comment by petrelharp** [comment]
Note the discussion here: https://tskit.dev/pyslim/docs/latest/metadata.html#converting-from-slim-time-to-tskit-time
