### ISSUE TITLE
provide subset argument to recapitate

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#23]
Suppose that we are only interested in a subset of the samples. For efficiency, we might want to recapitate only the subset of the initial population from which that subset inherits.  To do this, we only need to first mark those individuals we want to retain as samples, and then recaptiate.  For instance:
```
ts = pyslim.load("recipe_nonWF.trees")
tt = ts.tables
tt.nodes.set_columns(flags=[0 if k not in [20,21] else 1 for k in range(tt.nodes.num_rows)], 
          population=tt.nodes.population, individual=tt.nodes.individual, time=tt.nodes.time,
          metadata=tt.nodes.metadata, metadata_offset=tt.nodes.metadata_offset)
new_ts = pyslim.TreeSequence(tt.tree_sequence())
nts = new_ts.recapitate(recombination_rate=1.0)
```

We could do this as an argument, say `samples=` to `recapitate()`. I believe this doesn't do the extra work.

**Comment by petrelharp** [comment]
To do this, the cleanest way is just to have a function that easily allows re-marking who is a "sample". Here is a draft of this function:
```

def mark_samples(ts, samples, keep=True):
    '''
    Returns the same tree sequence except with the the nodes listed in `samples`
    marked as samples (keeping existing samples if `keep` is True).
    '''
    if (min(samples) < 0) or (max(samples) >= ts.num_nodes):
        raise ValueError("Illegal samples.")
    tables = ts.dump_tables()
    flags = tables.nodes.flags
    if not keep:
        flags = np.bitwise_or(flags, (~ msprime.NODE_IS_SAMPLE)).as_dtype("uint32")
    flags[samples] = np.bitwise_or(flags[samples], msprime.NODE_IS_SAMPLE).as_dtype("uint32")
    tables.nodes.set_columns(flags=flags, population=tables.nodes.population,
            individual=tables.nodes.individual, time=tables.nodes.time,
            metadata=tables.nodes.metadata, 
            metadata_offset=tables.nodes.metadata_offset)
    ts = tables.tree_sequence()
    return pyslim.SlimTreeSequence(ts)
```
so that someone wanting to do this right now could do
```
recap = mark_samples(ts, samples=samples, keep=False).recapitate()
```

**Comment by petrelharp** [comment]
Agree; I moved this to https://github.com/tskit-dev/msprime/issues/654 .

I think I'll leave this open, though, because passing in a `subset` argument is much more intuitive than having to first "mark samples".

**Comment by bhaller** [comment]
If the `tskit` issue gets fixed, IMHO this should be closed; that would then be the standard way to change the sample, and one wouldn't want to sprinkle `subset` arguments all over the API for individual calls to each change the sample in their own way.  Once the tskit issue is fixed I'd call this a doc bug at best – that the doc for this ought to mention using the new tskit method to change the sample first.

**Comment by petrelharp** [comment]
I agree - I'll close this. Anyhow, people could do this already by calling `simplify(..., keep_input_roots=True)`.
