### ISSUE TITLE
clean up requirements and test with windows?

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#232]
The versions in requirements/*.txt are out of date, no doubt. Figuring out how to build SLiM in the github workflow would be nice (important?) for stdpopsim, also.

**Comment by benjeffery** [comment]
`tskit-site` builds slim here:
https://github.com/tskit-dev/tskit-site/blob/main/.github/workflows/build-deploy.yml#L298

**Comment by andrewkern** [comment]
this was closed by #294
