### ISSUE TITLE
Redirect for docs object.inv

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/pyslim#238]
It might be helpful if https://pyslim.readthedocs.io/en/stable/objects.inv redirected to the new location, avoids broken builds on other projects.

**Comment by petrelharp** [comment]
Ah, thanks. Done!
![Screenshot from 2022-01-25 06-39-06](https://user-images.githubusercontent.com/1046249/150997546-7106a71f-4c8a-408c-8071-2c10d9eb57e8.png)
