### ISSUE TITLE
simplify() does some funny things on SLiM-generated treeSeqs

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/pyslim#24]
In particular:

1. Any nodes that are unrelated to all other sample nodes over the course of the simulation have all their edges removed.
2. It doesn't seem like you can specify arbitrary nodes as "samples" to be retained. I haven't been able to make it work with anything other than nodes from the latest generation.

A notebook showing this behaviour is [here](https://github.com/gtsambos/AdmixtureSim/blob/master/x.errors/5.testing-simplify.ipynb).

*EDIT:* I've now updated the notebook so it works, but the original commit is [here](https://github.com/gtsambos/AdmixtureSim/commit/4ee2893d3b003a6d1bc71e2789c16f0ac8e48a26#diff-778d55a3d89f1d73b4bbcee29a7ebd17).

**Comment by gtsambos** [comment]
Also, a feature request: I'd love to be able to use ```simplify()``` all the way back to a specified time rather than to the MRCA of the sample!

Ie. Input this...
![email2](https://user-images.githubusercontent.com/17755074/49489336-93068780-f89e-11e8-9d67-18daa0444093.jpeg)

... output this.
![email3](https://user-images.githubusercontent.com/17755074/49489342-9b5ec280-f89e-11e8-9e08-c013ba809562.jpeg)

**Comment by petrelharp** [comment]
> 1.    Any nodes that are unrelated to all other sample nodes over the course of the simulation have all their edges removed.

Sorry, I'm not getting it here - isn't this what `simplify()` should do?

> 2.    It doesn't seem like you can specify arbitrary nodes as "samples" to be retained. I haven't been able to make it work with anything other than nodes from the latest generation.

Right; that's because `simplify()` wants the `samples` to be actually *flagged* as `samples`, and in SLiM output only the final generation plus any Remembered individuals are flagged as samples. See the code above.

**Comment by petrelharp** [comment]
> Also, a feature request: I'd love to be able to use simplify() all the way back to a specified time rather than to the MRCA of the sample!

That's a nice idea.  It'd be a feature request for msprime, not for pyslim.  But, here's how I'd do it with existing tools: first, figure out which of the initial generation are ancestors of the samples you are interested in; then, mark only those as samples; then simplify.
```
# the nodes from today we want to keep
today = [30,31,32,33]
# the first generation
first_gen = [n.id for n in ts.nodes() if n.time == ts.slim_generation]
keep_first_gen = [False for _ in first_gen]

for t in ts.trees(sample_counts=True, tracked_samples=today):
    for k, n in enumerate(first_gen):
        if t.num_tracked_samples(n) > 0:
            keep_first_gen[k] = True

def add_samples(ts, samples):
    tabs = ts.tables
    new_flags = tabs.nodes.flags
    for x in samples:
        new_flags |= msprime.NODE_IS_SAMPLE
    tabs.nodes.set_columns(
            flags=new_flags,
            population=tabs.nodes.population,
            individual=tabs.nodes.individual,
            time=tabs.nodes.time,
            metadata=tabs.nodes.metadata,
            metadata_offset=tabs.nodes.metadata_offset)
    return tabs.tree_sequence()


keep_samples = today + [n for k,n in enumerate(first_gen) if keep_first_gen[k]]
simp4 = add_samples(ts, keep_samples).simplify(samples=keep_samples)
```

**Comment by gtsambos** [comment]
> Very nice, and thanks very much! The error that occurs in that document is because of this not-a-bug (usability bug?). Here is code that avoids it:

Great, thankyou! As I've mentioned via email, I've discovered that explicitly "remembering" the individuals at the beginning of the simulation fixes this problem too - the notebook's been updated now.

> Sorry, I'm not getting it here - isn't this what simplify() should do?

It's perhaps partly a style/interpretation thing; I think of ```simplify()``` as a means of simplifying a genealogy down to the smallest possible set of ancestors, rather than forcing the output of a tree with a single MCRA. I'm mostly concerned about the nodes that end up having no edges at all after simplification, like node 0 in the output of cell 6 [over here](https://github.com/gtsambos/AdmixtureSim/blob/master/x.errors/5.testing-simplify.ipynb). Dropping these "standalone" edges can mean you lose other important information - in this case, the population that the "standalone" node inherits from.

**Comment by petrelharp** [comment]
> Dropping these "standalone" edges can mean you lose other important information - in this case, the population that the "standalone" node inherits from.

Ok, gotcha. Keeping the ancestors would fix this, then.

**Comment by gtsambos** [comment]
> Ok, gotcha. Keeping the ancestors would fix this, then.

Yep! :)

**Comment by petrelharp** [comment]
No - Remembering them is cleaner. But, I wanted to record how you'd do it even if you hadn't Remembered them in the SLiM recipe.

**Comment by jeromekelleher** [comment]
Interesting thread! 

> Dropping these "standalone" edges can mean you lose other important information - in this case, the population that the "standalone" node inherits from.

Maybe this is the same as what we're talking about [here](https://github.com/tskit-dev/tskit/issues/1)? I.e., your "standalone" edges correspond to unary nodes on the path from samples back to a root?

**Comment by gtsambos** [comment]
Hi @jeromekelleher!

> Maybe this is the same as what we're talking about here? I.e., your "standalone" edges correspond to unary nodes on the path from samples back to a root?

Yep, very similar - for my purposes it would be sufficient to just show all of the roots, but all unary nodes along a path would also be super useful (I have been calling these "branches" in my work).

I guess the larger point here is that at present, ```simplify()``` converts treeSeqs that have been generated in msprime into other treeSeqs that looks like they've been generated in msprime. The treeSeqs generated by SLiM contain much more information (in fact - this is a major reason why some users, including me, may prefer to use SLiM for certain purposes), and it would be useful to be able to simplify these treeSeqs in certain ways without trimming them all the way back to an msprime-esque treeSeq.

**Comment by jeromekelleher** [comment]
Thanks @gtsambos, this is helpful. So it's pretty clear that we do need to figure out a less-drastic form of simplify that'll keep intermediate nodes. Unfortunately, I don't have time to work on this but I'd be happy to chat about it in more detail if you're interested in following it up.

**Comment by gtsambos** [comment]
Hey @jeromekelleher, I'd be keen to follow it up but perhaps not immediately, as it's not mission-critical to what I'm doing right now. Perhaps we could chat about it next year?

**Comment by jeromekelleher** [comment]
> Hey @jeromekelleher, I'd be keen to follow it up! I have a bit of other stuff on my plate right now, but it would be good to get your input before I do anything - perhaps we could chat about it early in the new year?

Sounds good to me @gtsambos!

**Comment by petrelharp** [comment]
This has been helpful discussion, but I think this issue could be closed - if there is something remaining, could you open a new issue for it, @gtsambos ?  I will close it; if you disagree then please reopen it.
