### ISSUE TITLE
could overlaying neutral mutations via treeseq overwrite simulated mutations in SliM?

### ISSUE THREAD

**Issue by DrK-Lo** [tskit-dev/pyslim#25]
I'm running replicate simulations, and in a subset of my simulations a few of the loci that I simulated in SliM do not have the expected allele frequencies and genotypes after overlaying neutral mutations with pyslim. In other words, the allele frequency at a position outputted from SliM does not match the allele frequency at that position after recapitation and overlaying neutral mutations. While this happens rarely, it appears to me that the process of recapitation and overlaying neutral mutations can in some cases overwrite the selected mutations output from SliM. Could this be happening or could there be something I'm missing?

**Comment by petrelharp** [comment]
Hm: it shouldn't happen. Could you post the code you are using, ideally with an example that produces the problem?

**Comment by DrK-Lo** [comment]
[a_process_trees.txt](https://github.com/tskit-dev/pyslim/files/2695838/a_process_trees.txt)

**Comment by DrK-Lo** [comment]
I will send you an example .trees file. In that file I have a mutation at site 144367  that according to my SliM output had an allele frequency of  0.6030 at the end of the simulation. After overlaying neutral mutations, the allele is pretty rare. There is another locus at 134502 whose allele frequency also changes, but only slightly. All the other mutations have the exact same allele frequency. 

You can run the script with (and be sure to change the script to `a_process_trees.py`, Markdown would only let me upload .txt files
```
i=10918
python3 a_process_trees.py -s ${i} > ${i}"_Invers_pytree.out" 2> ${i}"_Invers_pytree.error"
```

One thing that I noticed is that when simulating neutral mutations in SliM, sometimes I would get more than one mutation at the same position (because of the infinite sites model). But it appears that when overlaying neutral mutations with pyslim, I only get one mutation per position. Which is what made me think that maybe some simulated mutations were getting overwritten.

**Comment by DrK-Lo** [comment]
Also it just occurred to me that the issue could be in the vcf conversion in msprime, which would mean I am posting the issue in the wrong place...

**Comment by DrK-Lo** [comment]
[10918_Invers.trees.zip](https://github.com/tskit-dev/pyslim/files/2695873/10918_Invers.trees.zip)

**Comment by petrelharp** [comment]
I've checked, and the genotypes in those tree sequences at those sites are identical:
```
import msprime, pyslim
import numpy as np

ts = pyslim.load("10918_Invers.trees")
recap = ts.recapitate(recombination_rate=1e-05, Ne=1e3, random_seed=1)
mutated = msprime.mutate(recap, rate=1e-6, random_seed=1, keep=True)
treeseqs = [ts, recap, mutated]

check_positions = [144367, 134502] 

# check each position only occurs once in each tree sequence
sites = [[np.where(xts.tables.sites.position == x)[0] for x in check_positions] for xts in treeseqs]
for x in sites:
    for u in x:
        assert(len(u) == 1)

# check each position has only one mutation
mutations = [[xts.site(u[0]).mutations for u in s] for s,xts in zip(sites, treeseqs)]
for x in mutations:
    for u in x:
        assert(len(u) == 1)

def geno_by_position(ts, pos):
    assert(pos in ts.tables.sites.position)
    for var in ts.variants():
        if var.site.position == pos:
            break
    return var.genotypes

# check genotypes are the same
for pos in check_positions:
    genos = [geno_by_position(xts, pos) for xts in treeseqs]
    assert(all(genos[0] == genos[1]))
    assert(all(genos[0] == genos[2]))
    print([sum(x) for x in genos])
```

... so it appears to be in VCF output. I see that `mutated` has a position at `144366.71192197`, which rounds to `144367.`, that is probably the issue.

**Comment by DrK-Lo** [comment]
thank you so much Peter!

**Comment by petrelharp** [comment]
Ah-ha: and you'll notice in the VCF that there is a variant at position `144368`, although the next position in the tree sequence is `144381.77609599` - I think what has happened is that `write_vcf` has rounded positions, then bumped positions up to be unique. This should at least be documented; go ahead and open an issue for `msprime`.

**Comment by petrelharp** [comment]
Also see https://github.com/tskit-dev/msprime/issues/553 which would fix this.

**Comment by DrK-Lo** [comment]
Just to clarify - you think that the selected mutation that should be at site 144367 was bumped up to 144368?

**Comment by DrK-Lo** [comment]
I'll answer my own question - yes, I just confirmed it. thanks again Peter!
