### ISSUE TITLE
check for ts version in operations like pyslim.recapitate( )

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#250]
As noted by Chrystelle Delord in the [SLiM mailing list](https://groups.google.com/g/slim-discuss/c/WA-c1hUWgIY/m/G079po0EAwAJ?utm_medium=email&utm_source=footer), passing a SLiM v3.6 tree sequence to `pyslim.recapitate( )` can get a metadata validation error:
```
"MetadataValidationError: 'slim_id' is a required property
```
This wouldn't happen if the tree sequence was made into a SlimTreeSequence first, as that would update the metadata to the current version. But, we don't want to require that, so `pyslim.recapitate( )` ought to check for version and update if necessary.

Workarounds: do `pyslim.recapitate(pyslim.SlimTreeSequence(ts), ...)` or just use the current version of SLiM.

**Comment by bhaller** [comment]
Or it should at least give a better error message, if the full fix turns out to be hard.

**Comment by petrelharp** [comment]
This is done already, for instance: [here](https://github.com/tskit-dev/pyslim/blob/main/pyslim/methods.py#L47), with the function defined [here](https://github.com/tskit-dev/pyslim/blob/main/pyslim/slim_metadata.py#L857).  Thanks, former self!!
