### ISSUE TITLE
first() events can now do more stuff than before

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/pyslim#270]
Hey.  As discussed with you, first() events can now do more than they were allowed to do before.  Specifically, you can call treeSeqSimplify(), treeSeqRememberIndividuals(), treeSeqOutput(), addSubpop(), addSubpopSplit(), and readFromPopulationFile() in a first() event now.  There was really no reason to restrict those things except inertia, and it has turned out to be useful to be able to do them in first() events in two models I've written recently.  It seems to work fine in SLiM now, with my latest commit to the `multispecies` branch; I can remember individuals in first(), and roundtrip out to .trees and back, and everything is fine.  I think you said support for this additional time point would be needed in pyslim, though.  So I'm opening this issue for that.  :->  Let me know if you need anything further on my end!

**Comment by petrelharp** [comment]
This is closed in #277
