### ISSUE TITLE
Uses struct classes to avoid recompiling 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/pyslim#3]
Decoding metadata will be a bit more efficient if we create a decoder class for each of the types at module load time, e.g.
```python

individual_struct = struct.Struct("<iid") # or whatever

def decode_individual(buff):
     if len(buff) != individual_struct.size:
          raise ValueError(...)
     return individual_struct.unpack(buff)
```

https://docs.python.org/3.4/library/struct.html#classes

**Comment by petrelharp** [comment]
Don't think we can do this for the `Population` struct, which is of variable lenght, but there won't be very many of these anyhow.  Done in 3b8a3ff23f95ace9
