### ISSUE TITLE
Document workflow for adding/annotating a single mutation to msprime simulation

### ISSUE THREAD

**Issue by 35ajstern** [tskit-dev/pyslim#31]
This isn't an issue per se but a suggestion for a new feature (@petrelharp suggested I post it here); TLDR I think that for simulating selection from a standing variant it could be useful to have the option of throwing individual mutations onto the treeseq. Does such a method exist? I couldn't find it in the docs.
____

There’s a pretty straightforward way to simulate SSVs in Slim (the recipe is actually in the manual under a heading something like “Soft sweeps from a randomly selected locus”); you simulate neutrally with mutation until the start of selection, and then you randomly pick a segsite to be the selected allele from that time onward.

But I’m not totally sure how to implement something analogous with un-mutated, burn-in treeseqs. One naive way is to sample the allele frequency p at the start of selection from the SFS and randomly assign haplotypes the derived/ancestral allele w.p. p, 1-p, but this doesn’t model LD of the standing variant. I do have one idea for a recipe, but it seems like somewhat a pain to implement:

—In pyslim/msprime: simulate treeseqs corresponding to start of burnin up to just before the start of selection
—In pyslim/msprime: condition on the event that a particular locus (e.g. the basepair at the halfway point of the locus) is segregating at the start of selection; get the local tree at that locus. Randomly pick a branch w.p. proportional to the branch length. The allele frequency p is the number of leaves/haplotypes that subtend this branch.
—In slim: You assign the derived type (along with the desired selection coefficient) to the subtending haplotypes

but  I think this could be made easier is if there were simply a ts method to throw a mutation “by hand” onto a particular local tree; the pyslim docs hint at this but I’m not really sure how I would do this in practice. Any advice? How would you go about setting this up?

**Comment by petrelharp** [comment]
I think that this is maybe just a request for documentation (an additional example), although if we come across a function that would be useful, we could add it.

Here's my suggestion for how to do it, modifying yours:

1. Simulate a tree sequence with msprime.
2. Pick a tree proportional to total tree length multiplied by number of covered integers along the sequence (this is the same as adding mutations at some Poisson rate to the trees at integer sites and then picking one at random).
3. Add a mutation to a branch chosen proportional to length at a randomly chosen integer covered by that tree, and annotate it with SLiM metadata.
4. Load the tree sequence into SLiM, which should have a single segregating mutation.

How's that sound? If it seems good, I can suggest code.

**Comment by 35ajstern** [comment]
> Add a mutation to a branch chosen proportional to length at a randomly chosen integer covered by that tree, and annotate it with SLiM metadata.

This is what I'm curious about -- is there something in the pyslim/msprime API to do just this?

Thanks!

**Comment by petrelharp** [comment]
Here's something that does this. We need tools to do this more easily and with more error checking, but first we need to be able to add mutations at only integer sites, which needs non-infinite-sites mutation: [here](https://github.com/tskit-dev/msprime/issues/553).  But working through special cases like this is useful.

Here's some test code:
```
import pyslim, msprime
import numpy as np

ts = pyslim.annotate_defaults(msprime.simulate(10, recombination_rate = 0.1, length=100),
                              model_type="nonWF", slim_generation=1)

# find total tree length times sequence extent
tree_sizes = np.array([t.total_branch_length * (np.ceil(t.interval[1]) - np.ceil(t.interval[0])) for t in ts.trees()])
tree_sizes /= sum(tree_sizes)

# pick the tree
tree_index = np.random.choice(ts.num_trees, size=1, p=tree_sizes)
t = ts.first()
for _ in np.arange(tree_index):
    t.next()

assert(t.index == tree_index)

# pick the branch
treeloc = t.total_branch_length * np.random.uniform()
for mut_n in t.nodes():
    if mut_n != t.root:
        treeloc -= t.branch_length(mut_n)
        if treeloc <= 0:
            break

# pick the location on the sequence
mut_base = 0.0 + np.random.randint(low=np.ceil(t.interval[0]), high=np.ceil(t.interval[1]) - 1, size=1)

# the following assumes that there's no other mutations in the tree sequence
assert(ts.num_sites == 0)

# the mutation metadata
mut_md = pyslim.MutationMetadata(mutation_type=1, selection_coeff=0.0, population=1, slim_time=1)

tables = ts.tables
site_id = tables.sites.add_row(position=mut_base, ancestral_state=b'')
tables.mutations.add_row(site=site_id, node=mut_n, derived_state='1',
        metadata=pyslim.encode_mutation([mut_md]))


mut_ts = pyslim.load_tables(tables)

assert(mut_ts.num_sites == 1)

# genotypes
print(mut_ts.genotype_matrix())

mut_ts.dump("test.trees")
```

This can be loaded in without errors:
```
initialize()
{
    setSeed(23);
    initializeSLiMModelType("nonWF");
    initializeTreeSeq();
    initializeMutationRate(1e-2);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99);
    initializeRecombinationRate(1e-2);
}

1 early() { 
    sim.readFromPopulationFile("test.trees");
}

10 {
    catn("Done.");
    sim.simulationFinished();
}
```
... but I haven't done any more checking. Can you investigate?

**Comment by 35ajstern** [comment]
`for _ in np.arange(tree_index):
    t.next()`

is throwing an error: AttributeError: 'SparseTree' object has no attribute 'attrs'

I'm reading the pyslim docs to try to find what's going on.

**Comment by 35ajstern** [comment]
I just did a workaround using ts.trees() instead.

I believe the "high" argument in randint should be np.ceil(t.interval[1])  rather than np.ceil(t.interval[1]), too

**Comment by petrelharp** [comment]
> throwing an error:

maybe you need to update msprime?

> I believe the "high" argument in randint should be np.ceil(t.interval[1]) rather than np.ceil(t.interval[1])

What is the difference?

**Comment by 35ajstern** [comment]
I made a typo: the original version (which failed sometimes) was np.ceil(t.interval[1])-1
