### ISSUE TITLE
pyslim test run fails

### ISSUE THREAD

**Issue by SBNoor** [tskit-dev/pyslim#32]
I installed pyslim as mentioned in the readme document. However, when I ran the following command:

 python -m nose tests

it gives me the following error:
<img width="1436" alt="screenshot 2019-03-05 at 15 30 24" src="https://user-images.githubusercontent.com/23297354/53812372-a38cd380-3f5b-11e9-8293-2009091bda4d.png">

I installed SLiM and msprime as suggested. The test runs for SLiM are working and for msprime too. However when I do a test run for pyslim, it fails every time. I activate my msprime environment and then run the pyslim command. Could you tell me what possibly could be causing this?

**Comment by jeromekelleher** [comment]
This is because some internal APIs were moved to tskit with msprime 0.7.0. I'll open a PR to fix this in a minute.

I have the same error, so your installation is probably fine.

**Comment by SBNoor** [comment]
So do I need to install msprime again?

**Comment by jeromekelleher** [comment]
> So do I need to install msprime again?

No, I think your installation is fine, it's just some of the test cases are a little out of date.
