### ISSUE TITLE
edges are lost from tree sequence after SLiM step

### ISSUE THREAD

**Issue by ShyamieG** [tskit-dev/pyslim#331]
I wasn't entirely sure if this should be a SLiM issue or tskit issue - please let me know if I your think I should post this on the SLiM github instead.

I am finding that edges are being dropped from my tree sequence after passing it through a SLiM simulation. I have attached a full example [here](https://github.com/tskit-dev/tskit/files/12840913/check_edge_loss.zip). The SLiM code is complicated, but it runs in just a few minutes on my machine, and I wanted to provide a real subset of the problem I am facing 'in the wild'.

In this example, running the script 'run_hhar.sh' passes the tree sequence file 'inf-1602_V8865_to_H265_on_day_49.ts' to a SLiM script 'hhar.slim' and produces the output 'inf-1686_H265_to_V4533_on_day_39.ts', 'inf-1686_H265_to_V4861_on_day_162.ts', and 'inf-1686_H265_to_sample_on_day_168.ts'. Within SLiM, I have set simplify = F.

Next, the check_trees.py script loads the input and output trees and checks the history of 3 nodes (referenced by their SLiM ids) that should exist in all the trees. I simplify all the trees based on those 3 nodes, keeping all roots and internal nodes. Below are examples of the input and output trees across two intervals.

Input tree:
<img width="436" alt="input_tree" src="https://github.com/tskit-dev/tskit/assets/51133211/aafdbbf5-f933-449f-bf4d-e3a2e2ebb3b5">

One of the output trees:
<img width="434" alt="output_tree1" src="https://github.com/tskit-dev/tskit/assets/51133211/468c7207-5d79-4b6d-a984-473da43c7084">

From this, I can see that edges (e.g. the one connecting 41047010 and 45478074) and internal nodes (e.g. 41047010, 49821434) that existed in the input tree have been dropped in subsequent trees. Of note, the node 41047010 exists in the unsimplified output trees, but its relationship to its parent and child nodes is lost. The other two internal nodes (49821434, 45478102) are dropped entirely. It is not my intention for this to happen - if an edge exists at any point in the history of the sample nodes, I want that edge to be remembered across all subsequent SLiMulations that the tree sequences are passed through.

Any ideas about why this might be happening and how I can fix it?

edited to say that I'm using SLiM version 3.7.1 and tskit version 0.5.2

**Comment by ShyamieG** [comment]
I think this is what I was missing - thank you! I am trying this out now.

**Comment by petrelharp** [comment]
Say - can we close this issue, @ShyamieG ?

**Comment by ShyamieG** [comment]
Yes, I think so. I haven't finished testing this out because of all the other issues I've been running in to, but I will be sure to update once I've sorted them out.
