### ISSUE TITLE
Typo in `recapitate` function docstring

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/pyslim#347]
The documentation for the current version recapitate() function includes {meth}msprime.sim_ancestry, which should be modified, as no links are showing up.
https://tskit.dev/pyslim/docs/latest/python_api.html#pyslim.recapitate

**Comment by petrelharp** [comment]
Really? I'm not seeing that on my end - can you provide more info?
![Screenshot from 2024-07-01 16-14-57](https://github.com/tskit-dev/pyslim/assets/1046249/124baeb7-7081-40f0-97cc-a53d508aa0db)

**Comment by petrelharp** [comment]
Closed in #346 - thanks!!
