### ISSUE TITLE
provide method for getting the nodes that correspond to a set of individuals

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#39]
Proposal: this should be like:
```
def individual_nodes(inds):
  out = np.repeat(-1, len(inds) * 2).reshape((len(inds), 2))
  for k, ind in enumerate(inds):
    out[k, :] = self.individual(ind).nodes
```
so returns an array with one row per individual that can be flattened to get just a flat list of the nodes corresponding to the genomes of the individuals whose IDs are `inds`.

**Comment by jeromekelleher** [comment]
Worth having this within tskit I'd imagine? Proposal above does assume that all individuals have the same ploidy though, but I guess it could just fail if we have mixed ploidy inds.

**Comment by petrelharp** [comment]
> Worth having this within tskit I'd imagine? Proposal above does assume that all individuals have the same ploidy though, but I guess it could just fail if we have mixed ploidy inds.

Oh, totally. We could insert `tskit.NULL` for mixed ploidy.

Moved this to https://github.com/tskit-dev/tskit/issues/249
