### ISSUE TITLE
more intuitive overlap between handling of genetic data and individual metadata

### ISSUE THREAD

**Issue by gbradburd** [tskit-dev/pyslim#47]
Hi Peter!

This is a non-urgent request for either new tools, more documentation, or a tutorial for getting genetic data to match up more intuitively to individual data in pyslim.  Some areas of (my) confusion that cropped up in trying to run some nonWF simulations for diploids with tree sequence recording:

1. The individuals included in .genotype_matrix or output by .write_vcf are only the ones flagged as `samples`, while .individual_locations or .individual_times output data for _everyone_. So standard stuff like running a spatial sim and outputting a location and a genotype for each sampled individual requires some hoop-jumpery to output only the metadata for the sample-flagged individual set.

2. The order of the genetic data contained in .genotype_matrix() or output by .write_vcf is determined by the numbering of the nodes associated with the individuals flagged as samples, but the ordering of .individual_locations or .individual_times is determined by individual ID.  This is maybe extra confusing, as the sample names associated with each sample in .write_vcf() aren't informative (ie don't match back to individual metadata).

Hope those are clear - happy to write more about what I was trying to do and where I got mired.  And again - not urgent!  Just wanted to add it to the wishlist...

-g

**Comment by petrelharp** [comment]
Thanks! I'm a little unclear on what exactly the example workflow should be, though. How's this?

1. Simulate data with SLiM
2. Recapitate, mutate, etcetera
3. Take a subsample of the modern individuals
4. Get these individual locations and make a map
5. Compute divergences between individuals using tskit, and plot against geographic distance
6. Write out a VCF file of these individual genotypes for use by other programs

... would that cover things? Want to suggest any other steps?

**Comment by gbradburd** [comment]
Yeah that covers a lot of it.  I'd add (in **bold**):

1. Simulate data with SLiM
2. Recapitate, mutate, etcetera
3. Take a subsample of the modern individuals
**or historical individuals(as remembered in the SLiM model)**
4. Get these individual locations and make a map
5. Compute divergences between individuals using tskit, and plot against geographic distance
**and write out divergences for use by other programs**
6. Write out a VCF file of these individual genotypes for use by other programs
7. **Write out locations/times/metadata of these individuals for use by other programs in a way that makes it easy to match up to genetic data (divergences or genotypes) to metadata, either because they have the same order, or because both sets of output can be associated with individual IDs**

Does that make more sense?  Thanks Peter!

**Comment by petrelharp** [comment]
This got done in #48, I think.
