### ISSUE TITLE
[docs] recapitation description ungrammatical

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/pyslim#63]
As reported [here](https://github.com/tskit-dev/tskit/issues/458#issuecomment-581152719) by @winni2k:

>> To allow this process, the first generation of the SLiM simulation has been recorded in the tree sequence, but are not currently marked as samples, so this process (or, simplify()) will remove any of these that are not needed. If you want to keep them, then set keep_first_generation to True; although this will make more work here.

> There's a grammar mistake in the first sentence, but I don't understand the sentence enough to fix it.

**Comment by petrelharp** [comment]
Editing [this](https://pyslim.readthedocs.io/en/latest/python_api.html#pyslim.SlimTreeSequence.recapitate):

>  To allow recapitation to be done correctly, the individuals of the first generation of the SLiM simulation have been recorded in the tree sequence, but are not marked as samples. This method (or, simplify()) will remove any non-samples that are not needed to describe the resulting trees, so you want to keep them, then set keep_first_generation to True.

Thanks for the report! Does this clear things up, @winni2k?

**Comment by winni2k** [comment]
That actually is a lot better. Thanks!
