### ISSUE TITLE
Getting the TMRCA from a subset of extant individuals

### ISSUE THREAD

**Issue by aritra90** [tskit-dev/pyslim#66]
Hi, 

I am trying to obtain the TMRCA of a subset of extant individuals from the tree sequence  ARG generated by pyslim. I am kinda lost in the documentation of tskit and msprime to figure out whether the tmrca() function can suffice (although, it takes two node arguments). Any help would be appreciated on this as I understand this should be straightforward. 

I am loading the .trees file and then passing a list of samples as: 
```
ts = pyslim.load("./recipeX.trees")
samples = random.sample(range(0,999),25)
subsample_ts = ts.simplify(samples = samples)
```
Thereafter, I just need to find the TMRCA for these selected samples.

Thanks.

**Comment by molpopgen** [comment]
For sample sizes larger thant 2, my instinct is to simplify with respect to the samples and then look at the root times of all trees.

**Comment by jeromekelleher** [comment]
The simplest thing to do is 
```python
tmrcas = [subsample_ts.node(tree.root).time for tree in subsample_ts.trees()]
```
this gives the TMRCAs tree-by-tree. Note that you might have multiple roots per tree though, if the samples haven't fully coalesced (in which case this will raise an error).

**Comment by aritra90** [comment]
Thanks @jeromekelleher that is indeed simple. However, as you mention I almost always get the multiple roots per tree error. 
I tried saving the .trees file when a coalescence was guaranteed such as in:
```
initialize()
{
        initializeTreeSeq(checkCoalescence=T);
        initializeMutationRate(1e-7);
        initializeMutationType("m1",0.5,"f",0.0);
        initializeGenomicElementType("g1",m1,1.0);
        initializeGenomicElement(g1,0,75000);
        initializeRecombinationRate(1e-8);
        initializeSex("A");
}

1
{
        sim.addSubpop("p1",500);
}

1: late(){
        if(sim.treeSeqCoalesced())
        {
                catn(sim.generation + ": COALESCED");
                sim.treeSeqOutput("./recipeX.trees");
                sim.simulationFinished();
        }
}
```
and thereafter trying to find the TMRCA. However, the same error occurred. Can you provide an insight?

**Comment by jeromekelleher** [comment]
I can't really add any insight into what SLiM is doing here I'm afraid (I don't really know it). But, you could get the TMRCA of all the roots, using ``tree.roots`` rather than ``tree.root``.

**Comment by aritra90** [comment]
Thanks!

**Comment by petrelharp** [comment]
You don't want to look at the ages of the roots - for instance, every individual present at the start of the slim simulation is [present in the tree sequence](https://pyslim.readthedocs.io/en/latest/tutorial.html#possibly-important-technical-notes) until you simplify. So, you should probably use root.time *after* you simplify.

But, also note that stopping *at* coalescence is not a good idea - that's a special time. This is discussed in more detail in the SLiM manual.
