### ISSUE TITLE
output VCF with legal REF/ALT columns

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#73]
Currently we write out the ancestral state and derived state in the REF and ALT columns of the VCF file. These can be anything, for instance (from SLiM):
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	tsk_0	tsk_1	tsk_2	tsk_3	tsk_4	tsk_5	tsk_6	tsk_7	tsk_8	tsk_9
1	735760	.		16823049	.	PASS	.	GT	1|0	1|0	0|1	0|1	1|1	0|0	0|1	1|1	0|1	1|1
1	735786	.		0	.	PASS	.	GT	1|1	1|1	1|1	1|1	1|1	1|1	1|1	1|1	1|1	1|1
1	878418	.		42,956113,42	.	PASS	.	GT	2|2	2|2	2|2	2|2	2|2	2|2	2|2	2|2	2|2	2|2
```
 Unfortunately, (IIRC) the standard for VCF files says that REF and ALT need to be strings of nucleotides:
![vcf](https://user-images.githubusercontent.com/1046249/77674505-f1022700-6f48-11ea-965c-1cfae6596423.png)

This was brought up [here](https://github.com/tskit-dev/pyslim/issues/65) as well, but more investigation by @attrna found a number of VCF parsing software that can't deal with it (eg picard, gatk, vcftools).

I'm not sure what to do here, really. Suggestions?

**Comment by attrna** [comment]
Hi! Also, there's another connected issue. One vcf column is missing:

```
##fileformat=VCFv4.2
##source=tskit 0.2.4.dev0
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=3000000>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  tsk_0
1       578     .       0       1       .       PASS    .       GT      0|0
1       997     .               781024  .       PASS    .       GT      1|1
1       1665    .       0       1       .       PASS    .       GT      0|0
1       5278    .               3297755 .       PASS    .       GT      0|0
```

All rows with the ancestral allele information don't have the ALT column. It should be:

 `1       5278    .               3297755       **something_else**       .       PASS    .       GT      0|0
`

**Comment by petrelharp** [comment]
The column is there, but has the empty string in, I believe?

**Comment by attrna** [comment]
Oh, that's right. After the ID column is \t\t, so actualy the REF column is empty

**Comment by petrelharp** [comment]
Yes - which is correct - since the ancestral state is the empty string.

**Comment by petrelharp** [comment]
Proposal: Nucleotide models we can just output their nucleotides. For non-nucleotide models, at each site, collect the alleles, sort them, and translate them into strings of ACGT by converting their rank to base 4. (so, 1,2,3,..., converts to A,T,C,G,AA,AC,AT,...)  For instance, if a site has ancestral allele `""` and derived allele `123` then these will be converted to `A` and `C`. If another site had ancestral allele `""` and derived alleles `5`, `5,7`, `5,72`, `123`, and `123,6`, then these will be converted to `A`, `T`, `AA`, `AC`, `C`, and `T` respectively (if I did the sorting of those strings right anyhow). We could put the info in the INFO column, as @attrna suggests, but personally I may skip that, and recommend people use the tree sequence if they want to get down to that level of detail.

**Comment by attrna** [comment]
Sounds good to me! I agree many things can be done with tree-sequences now. I guess, people still want to use some external tools or maybe compare the results of analyses. I think you are right, I don't know any tool that can use this information, and the alleles are already polarized to the ancestral one, so maybe it's worth to save some space. The origin is useful to recover info on local haplotypes or something like that, I agree it's better to extract it for the regions of interest from the tree-sequences directly. Thank you!!

**Comment by petrelharp** [comment]
People will definitely need VCFs!  I'm not opposed to someone putting that stuff in the INFO field, but I don't think I'll do it now, at least without knowing that anyone would actually use it.

**Comment by petrelharp** [comment]
Note: remember to update the VCF example in vignette_space.
