### ISSUE TITLE
GitHub releases?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/pyslim#74]
There doesn't seem to be releases tagged on GitHub for the last few releases - this can be confusing for people looking for info about them (I was looking for 0.401, was confused when it wasn't there).

Also, it doesn't look like there's a changelog - this would also be useful. We're probably going to need to make some coordinated releases between msprime, tskit, SLim and pyslim soon so it would help to have more info about releases.

I would also vote for a standard [semver](https://semver.org/) release numbering system.

**Comment by petrelharp** [comment]
>  releases tagged on GitHub 

Whoops, I forgot I had to `git push --tags`. That's done.

> I would also vote for a standard semver release numbering system.

omg, yes. My plan is to deal with a bunch of the outstanding issues, call it 1.0, and turn over a new versioning leaf.

> changelog

Also, yes! Added.

Also, I need to set up codecov and circleCI and release to conda-forge.  I'll close this issue, though.  Thanks for bugging me.
