### ISSUE TITLE
Recapitation and recombination maps

### ISSUE THREAD

**Issue by qlangdon** [tskit-dev/pyslim#78]
Hi,

I'm trying to use the recapitate function with a recombination map that matches what was used for the SLiM simulation. I modified the recombination map to match the Hapmap style and am able to read the recombination map in using msprime.RecombinationMap.read_hapmap(). However when I try to use this to recapitulate my SLiM treeSeq output (using ts.recapitate(recombination_map=recomb_map, Ne=25000)) I receive the following error:

_msprime.InputError: Input error in initialise: The specified recombination map is cannot translate the coordinates for the specified tree sequence. It is either too coarse (num_loci is too small) or contains zero recombination rates. Please either increase the number of loci or recombination rate

In my recombination map there are no zero recombination rates other than the final line and the number of loci seems to be reasonable: recomb_map.get_num_loci() = 4294967295. 

I have attached the hapmap style recombination map I'm trying to use and the recombination map I used for the SLiM simulation.

I am unsure what the underlying issue is that is producing the error and how I can fix it so I can simulate and recapitulate with the same recombination map. Any advice would be helpful.

Thanks!
Quinn
[Recmap_SLiM_chr2_hapmap_style.txt](https://github.com/tskit-dev/pyslim/files/4542714/Recmap_SLiM_chr2_hapmap_style.txt)

[SLiM-ready-recmap-ScyDAA6-1196-HRSCAF-1406.txt](https://github.com/tskit-dev/pyslim/files/4542724/SLiM-ready-recmap-ScyDAA6-1196-HRSCAF-1406.txt)

**Comment by petrelharp** [comment]
Well, I was expecting an error, because we haven't worked with recombination maps much yet... but it seems to be working for me. I'll need some more information. If you'd posted your code I might have spotted something wrong? Here's a minimal working example, that works for me:

In `hapmap.txt`
```
Chromosome	Position(bp)	Rate(cM/Mb)	Map(cM)
chr2	14983	1e-06	0
chr2	15573	0.219075477056277	0.00025016
chr2	28795	0.219075477056277	0.005856288
chr2	31261	0.110571113419913	0.006384012
chr2	44817	0.00164823295238095	0.00642725564
chr2	48430	0.0016585667012987	0.00643885337
chr2	48595	0.00172056919480519	0.00643940282
chr2	48818	0.00177223793939394	0.00644016771
chr2	49148	0.00246976599134199	0.00644174511
chr2	49170	0.0028727821991342	0.00644186743
chr2	50000	0.0	0.00644186743
```
and in `slim_map.txt`:
```
0	14983
4.24E-09	15573
4.24E-09	28795
2.14E-09	31261
3.19E-11	44817
3.21E-11	48430
3.33E-11	48595
3.43E-11	48818
4.78E-11	49148
5.56E-11	49170
0	50000
```
and here's a slim script:
```
initialize()
{
    // read recomb map
    recfile = readFile('slim_map.txt');
    recpos = integer(length(recfile));
    recrate = float(length(recfile));
    for (k in seqLen(length(recfile))) {
        line = strsplit(recfile[k], "\t");
        recrate[k] = asFloat(line[0]);
        recpos[k] = asInteger(line[1]) - 1;
    }

    setSeed(23);
    initializeTreeSeq();
    initializeMutationRate(1e-2);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, recpos[length(recpos)-1]);
    initializeRecombinationRate(recrate, recpos);
}

1 { 
    sim.addSubpop("p1", 10);
}

10 {
    sim.treeSeqOutput("slim.trees");
    catn("Done.");
    sim.simulationFinished();
}
```
and the python:
```
import pyslim, msprime

ts = pyslim.load("slim.trees")
map = msprime.RecombinationMap.read_hapmap("hapmap.txt")
assert(map.get_length() == ts.sequence_length)

rts = ts.recapitate(Ne=10, recombination_map=map)
print(rts.num_trees)
```

... but, I'm using the development versions of pyslim and msprime. We've modified some of this stuff recently, so the answer might be that you need to update. Could you run this code and tell me what happens?

**Comment by qlangdon** [comment]
Sorry for the slow response. I tested this code and it worked, yay! But
then I got caught up in testing variations on this. I'd like to be able to
use the recapitulation with a simulation starting with two populations and
that still seems to be an issue with memory and runtime. Can
recapitulation be used with multiple populations or can it only be used
with simulations with one starting population?
Thanks again!
Quinn

**Comment by petrelharp** [comment]
> I tested this code and it worked, yay! 

Glad to hear it! If there's a wa to help other avoid whatever problem you got into, let me know.

> Can recapitulation be used with multiple populations or can it only be used
with simulations with one starting population?

Yes! The `ts.recapitate( )` method takes all the arguments as `msprime.simulate( )` -- it's just a thin wrapper around `msprime.simulate(from_ts=ts, ...)` -- so you can recapitate with whatever demographic history that is representable in msprime. However, I haven't written up an example of this yet - it's on the list, though, #53 - any assisitance is welcome.  I'd recommend starting with the documentation for `msprime.simulate( )`. Or, if you post a small, simple example to #53 asking how to do X, then I could respond there.

It seems like your initial issue was resolved so I'll close this now - but please re-open if it is not!
