### ISSUE TITLE
provide method for assigning individuals to populations

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#8]
This could be an argument of the form `population`, giving a vector of population IDs, or it could be a dictionary of individual : population IDs, or it could be a dictionary of population ID : list of individual IDs, or... ?

**Comment by bhaller** [comment]
When this is implemented, it would be nice to modify recipe 16.9 to show how to do it.

**Comment by petrelharp** [comment]
I don't think we really need this, as you'd do this by setting up the msprime demography.
