### ISSUE TITLE
example of extracting information for different mutation types

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#80]
e.g. allele frequencies of neutral versus selected mutations. Note that mutation stacking makes this a bit tricky.

**Comment by hyanwong** [comment]
Not that you are likely to forget this, but the pyslim tutorial currently says "currently msprime only produces mutations with an infinite-sites model" - which with your changes is no longer true, so that bit will need a little work too (presumably when #77 is closed?)

**Comment by jeromekelleher** [comment]
Should wait until msprime 1.0 is released, though.

**Comment by petrelharp** [comment]
This is in the docs now, in `tutorial.md` under "Extracting information about selected mutations"
