### ISSUE TITLE
stage and remembered_stage for individuals_at_age( ) & individuals_alive at()

### ISSUE THREAD

**Issue by santaci** [tskit-dev/pyslim#90]
This is mostly a question related to what the documentation shows and the most recent release. 

I have upgraded to version 0.401 of pyslim (using pip) but am unable to use the features that show up under the "latest" documentation such as `individuals_at_age(time, stage, remembered_stage) ` I can only use `individuals_at_age(time)`. Should I be upgrading using the github version to have these features?

**Comment by petrelharp** [comment]
Hello! Yes - that's right, and installing from github will work fine. But, I'm going to be pushing a new release sometime this week (that goes along with an updated tskit and SLiM).

**Comment by petrelharp** [comment]
I've added a note about this, to the next release: 37c5fe13d3. Please let me know if this is confusing or should be somewhere else.
