### ISSUE TITLE
actually deprecate old metadata structures

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/pyslim#96]
Although pyslim uses the new metadata stuff, it serves up metadata as structures (eg NodeMetadata objects) rather than just using the dicts that tskit gives us. This is only for backwards compatibility - all the same information is there and the UI is minimally different - and it'd be real nice to GET RID of all this now-superfluous code. But I hadn't thought of a good way to do this.

One important reason to shift to being compatible is that the conflict in notation between tskit and pyslim is super confusing: right now if ts is a TreeSequence you do `node.metadata['slim_id']`, whereas if its a SlimTreeSequence you do `node.metadata.slim_id`.

But now, I think I have a good way to deprecate the old stuff. I could add a `legacy_metadata=False` argument to `pyslim.load( )`, that if `True` would return the old-style metadata, and be removed at some point in the future. This would mean that existing scripts that use metadata would break, but only require adding `legacy_metadata=True` to any calls to `load()` to keep working. (Or, better, going through and changing `node.metadata.slim_id` to `node.metadata['slim_id']`.)

How's this sound?

**Comment by bhaller** [comment]
Can the error message given, for old code that needs to be updated, be clear and descriptive, saying what has happened and what the user needs to do to get their code working again?
